test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon_staging:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws_staging, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws_staging, :secret_access_key) %>
  region: eu-west-2
  bucket: exlibris-staging

amazon_production:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws_production, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws_production, :secret_access_key) %>
  region: eu-west-2
  bucket: exlibris-production
